### ISSUE TITLE
运行时报错，请问这个参数是需要怎么设置？

### ISSUE THREAD

**Issue by xiatian815** [Frank-Wang-oss/FCSTGNN#1]
$ python main_HAR.py
Traceback (most recent call last):
  File "main_HAR.py", line 166, in <module>
    train = Train(args)
  File "main_HAR.py", line 22, in __init__
    self.train, self.valid, self.test = data_generator('E:\FC_STGNN\data\HAR', args=args)
  File "E:\FC_STGNN\data_loader_HAR.py", line 49, in data_generator
    train_dataset = Load_Dataset(train_dataset, args)
  File "E:\FC_STGNN\data_loader_HAR.py", line 32, in __init__
    self.x_data = self.x_data.reshape(shape[0],shape[1],args.time_denpen_len, args.window_size)
AttributeError: 'Namespace' object has no attribute 'window_size'
(gpu-torch)

**Comment by Frank-Wang-oss** [comment]
Sorry for the late reply. This hyper-parameter 'window_size' should be 'patch_size'. Thanks for pointing out this problem.

**Comment by Frank-Wang-oss** [comment]
We have updated and revised this problem.

**Comment by xiatian815** [comment]
这个也有报错

**Comment by xiatian815** [comment]
请求的数组形状变得不均匀
